# Generated by Django 6.0.7 on 2026-07-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('huggingface', 'HuggingFace (in-process)')], default='ollama', max_length=32, verbose_name='provider')),
                ('model_name', models.CharField(default='bge-m3', max_length=120, verbose_name='modello')),
                ('dimension', models.PositiveIntegerField(default=1024, help_text='Misurata in P0 su bge-m3: 1024. La colonna pgvector creata da langchain-postgres non dichiara la dimensione, quindi il database NON impone la coerenza: profili con dimensioni diverse vanno tenuti su collezioni diverse.', verbose_name='dimensione del vettore')),
                ('normalize', models.BooleanField(default=True, verbose_name='normalizza')),
                ('batch_size', models.PositiveIntegerField(default=16, help_text="Chunk per chiamata di embedding. In P0 il costo a caldo e' ~0,4 s/chunk.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='dimensione del lotto')),
            ],
            options={
                'verbose_name': 'profilo di embedding',
                'verbose_name_plural': 'profili di embedding',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('system_prompt', models.TextField(default="Sei un assistente che risponde ESCLUSIVAMENTE sulla base del contesto fornito. Se il contesto non contiene l'informazione, rispondi esattamente: 'Non dispongo di questa informazione nei documenti forniti.' Rispondi in italiano, in modo conciso.", help_text='Verificato in P0: con questo testo il modello dichiara di non sapere invece di inventare, anche ricevendo contesto irrilevante (CA-4).', verbose_name='prompt di sistema')),
                ('template', models.TextField(default='Contesto:\n{context}\n\nDomanda: {question}', help_text='Deve contenere i segnaposto {context} e {question}.', verbose_name='template')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompt',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChunkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('splitter', models.CharField(choices=[('recursive', 'Recursive character'), ('token', 'Basato su token')], default='recursive', max_length=32, verbose_name='strategia')),
                ('chunk_size', models.PositiveIntegerField(default=800, validators=[django.core.validators.MinValueValidator(50)], verbose_name='dimensione del segmento')),
                ('chunk_overlap', models.PositiveIntegerField(default=120, verbose_name='sovrapposizione')),
                ('separators', models.JSONField(blank=True, default=list, help_text='Elenco JSON di stringhe, in ordine di priorita\'. Esempio: ["\\n\\n", "\\n", " ", ""]. Vuoto = separatori predefiniti dello splitter.', verbose_name='separatori')),
            ],
            options={
                'verbose_name': 'profilo di segmentazione',
                'verbose_name_plural': 'profili di segmentazione',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('chunk_overlap__lt', models.F('chunk_size'))), name='chunkingprofile_overlap_minore_di_size', violation_error_message='La sovrapposizione deve essere inferiore alla dimensione del segmento, altrimenti la segmentazione non avanza.')],
            },
        ),
        migrations.CreateModel(
            name='LLMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai_compatible', 'API OpenAI-compatibile')], default='ollama', max_length=32, verbose_name='provider')),
                ('base_url', models.URLField(default='http://localhost:11434', help_text="Endpoint del servizio di inferenza. Cambiarlo sposta la generazione su un altro host: e' cio' che rende il sistema riconfigurabile, ed e' anche l'unica falla dichiarata nella garanzia di non esfiltrazione (ARCHITECTURE §8.2 e §9).", verbose_name='base URL')),
                ('model_name', models.CharField(default='qwen2.5:7b-instruct', max_length=120, verbose_name='modello')),
                ('temperature', models.FloatField(default=0.0, help_text="0 = deterministico. Verificato in P0: a 0 la risposta e' riproducibile.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='temperatura')),
                ('top_p', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='top-p')),
                ('top_k', models.PositiveIntegerField(default=40, verbose_name='top-k')),
                ('max_tokens', models.PositiveIntegerField(default=1024, verbose_name='token massimi')),
                ('timeout_s', models.PositiveIntegerField(default=180, help_text="Il primo caricamento del modello in VRAM ha richiesto fino a 156 s in P0, e il cold start si ripresenta a meta' sessione per contesa di VRAM. Non scendere sotto i 180 s.", verbose_name='timeout (s)')),
                ('is_default', models.BooleanField(default=False, verbose_name='predefinito')),
            ],
            options={
                'verbose_name': 'profilo LLM',
                'verbose_name_plural': 'profili LLM',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('temperature__gte', 0), ('temperature__lte', 2)), name='llmprofile_temperatura_0_2', violation_error_message='La temperatura deve essere compresa fra 0 e 2.'), models.CheckConstraint(condition=models.Q(('top_p__gte', 0), ('top_p__lte', 1)), name='llmprofile_top_p_0_1', violation_error_message='top-p deve essere compreso fra 0 e 1.'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='llmprofile_unico_predefinito', violation_error_message="Esiste gia' un profilo LLM predefinito: toglierlo da quello attuale prima di designarne un altro.")],
            },
        ),
        migrations.CreateModel(
            name='RetrievalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('search_type', models.CharField(choices=[('similarity', "Similarita'"), ('mmr', 'MMR (diversificata)'), ('similarity_score_threshold', "Similarita' con soglia")], default='similarity', max_length=32, verbose_name='strategia')),
                ('top_k', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='segmenti recuperati')),
                ('fetch_k', models.PositiveIntegerField(default=20, help_text='Usato solo da MMR: quanti candidati recuperare prima di diversificare.', verbose_name='candidati esaminati (MMR)')),
                ('lambda_mult', models.FloatField(default=0.5, help_text="1 = massima pertinenza, 0 = massima diversita'.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='lambda (MMR)')),
                ('score_threshold', models.FloatField(default=0.5, help_text="Usata solo dalla strategia «Similarita' con soglia» (RF-14).", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='soglia di punteggio')),
            ],
            options={
                'verbose_name': 'profilo di recupero',
                'verbose_name_plural': 'profili di recupero',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fetch_k__gte', models.F('top_k'))), name='retrievalprofile_fetch_k_gte_top_k', violation_error_message='I candidati esaminati non possono essere meno dei segmenti restituiti.'), models.CheckConstraint(condition=models.Q(('lambda_mult__gte', 0), ('lambda_mult__lte', 1)), name='retrievalprofile_lambda_0_1', violation_error_message='Lambda deve essere compreso fra 0 e 1.'), models.CheckConstraint(condition=models.Q(('score_threshold__gte', 0), ('score_threshold__lte', 1)), name='retrievalprofile_soglia_0_1', violation_error_message='La soglia deve essere compresa fra 0 e 1.')],
            },
        ),
    ]
