# Generated by Django 6.0.7 on 2026-07-24 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_profili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Solo PDF. I PDF scansionati senza testo verranno rifiutati in fase di ingestione (RF-10).', upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nome originale')),
                ('checksum', models.CharField(blank=True, db_index=True, help_text="SHA-256 del file. Calcolato dall'ingestione (T-20), vuoto finche' il documento non e' stato elaborato.", max_length=64, verbose_name='checksum')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('indexed', 'Indicizzato'), ('failed', 'Fallito')], db_index=True, default='pending', max_length=16, verbose_name='stato')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='pagine')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='segmenti')),
                ('error_message', models.TextField(blank=True, verbose_name='errore')),
                ('index_fingerprint', models.CharField(blank=True, help_text="Hash dei valori dei profili al momento dell'indicizzazione.", max_length=64, verbose_name="impronta dell'indice")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='caricato il')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='indicizzato il')),
                ('indexed_chunking_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rag.chunkingprofile', verbose_name='profilo di segmentazione usato')),
                ('indexed_embedding_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rag.embeddingprofile', verbose_name='profilo di embedding usato')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documenti',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(verbose_name='ordinale')),
                ('page_number', models.PositiveIntegerField(verbose_name='pagina')),
                ('content', models.TextField(verbose_name='contenuto')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='caratteri')),
                ('vector_id', models.CharField(blank=True, db_index=True, help_text="Corrisponde a langchain_pg_embedding.id, che in P0 e' risultato di tipo character varying e non uuid: qui e' quindi una stringa.", max_length=64, verbose_name='id del vettore')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'segmento',
                'verbose_name_plural': 'segmenti',
                'ordering': ['document', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('collection_name', models.CharField(help_text='Nome della collezione in pgvector. Profili di embedding diversi DEVONO stare su collezioni diverse: la colonna dei vettori non dichiara la dimensione, quindi il database non li separerebbe.', max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Solo minuscole, cifre e underscore; deve iniziare per lettera.')], verbose_name='nome della collezione')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('chunking_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to='rag.chunkingprofile', verbose_name='profilo di segmentazione')),
                ('embedding_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to='rag.embeddingprofile', verbose_name='profilo di embedding')),
            ],
            options={
                'verbose_name': 'base di conoscenza',
                'verbose_name_plural': 'basi di conoscenza',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.knowledgebase', verbose_name='base di conoscenza'),
        ),
        migrations.CreateModel(
            name='RagPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='attiva')),
                ('is_default', models.BooleanField(default=False, verbose_name='predefinita')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='rag.knowledgebase', verbose_name='base di conoscenza')),
                ('llm_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='rag.llmprofile', verbose_name='profilo LLM')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='rag.prompttemplate', verbose_name='prompt')),
                ('retrieval_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='rag.retrievalprofile', verbose_name='profilo di recupero')),
            ],
            options={
                'verbose_name': 'pipeline RAG',
                'verbose_name_plural': 'pipeline RAG',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='domanda')),
                ('answer', models.TextField(blank=True, verbose_name='risposta')),
                ('retrieval_ms', models.PositiveIntegerField(default=0, verbose_name='recupero (ms)')),
                ('generation_ms', models.PositiveIntegerField(default=0, verbose_name='generazione (ms)')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='totale (ms)')),
                ('error', models.TextField(blank=True, verbose_name='errore')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='eseguita il')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='rag.ragpipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'interrogazione',
                'verbose_name_plural': 'interrogazioni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='posizione')),
                ('score', models.FloatField(verbose_name='punteggio')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrievals', to='rag.documentchunk', verbose_name='segmento')),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_chunks', to='rag.querylog', verbose_name='interrogazione')),
            ],
            options={
                'verbose_name': 'segmento recuperato',
                'verbose_name_plural': 'segmenti recuperati',
                'ordering': ['query_log', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'ordinal'), name='documentchunk_ordinale_unico_per_documento'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum', ''), _negated=True), fields=('knowledge_base', 'checksum'), name='document_checksum_unico_per_kb', violation_error_message="Questo file e' gia' presente in questa base di conoscenza."),
        ),
        migrations.AddConstraint(
            model_name='ragpipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='ragpipeline_unica_predefinita', violation_error_message="Esiste gia' una pipeline predefinita: toglierlo da quella attuale prima di designarne un'altra."),
        ),
        migrations.AddConstraint(
            model_name='retrievedchunk',
            constraint=models.UniqueConstraint(fields=('query_log', 'rank'), name='retrievedchunk_posizione_unica_per_query'),
        ),
    ]
